INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (1,51,"Silas Hester","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (2,38,"Burton Justice","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (3,28,"Kiayada Contreras","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (4,39,"Jeanette Lawson","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (5,70,"Eve Leon","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (6,53,"Melvin Carver","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (7,33,"Nasim Andrews","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (8,58,"Daryl Pitts","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (9,87,"Luke Collier","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (10,31,"Rinah Cooke","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (11,67,"Kibo Anthony","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (12,89,"Tate Hyde","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (13,93,"Craig Moody","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (14,3,"Colton Duke","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (15,6,"Colin Obrien","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (16,47,"Devin Bridges","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (17,65,"Silas Henson","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (18,5,"Candice Sheppard","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (19,31,"Ulysses Mueller","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (20,28,"Cairo Quinn","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (21,93,"Zeus Harvey","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (22,36,"Justina Beck","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (23,74,"Avye Austin","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (24,78,"Adria Murphy","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (25,43,"Eric Russo","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (26,83,"Buckminster Hahn","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (27,8,"Clayton Torres","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (28,55,"Dieter Brewer","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (29,98,"Breanna Vinson","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (30,5,"Ella Wheeler","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (31,87,"Kai Barr","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (32,85,"Burton Hansen","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (33,28,"Brooke Koch","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (34,97,"Ryder Alston","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (35,95,"TaShya Wade","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (36,65,"Channing Hayes","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (37,29,"Lysandra Bray","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (38,68,"William Hogan","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (39,50,"Zelda Barron","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (40,3,"TaShya Wagner","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (41,56,"Amber Mcleod","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (42,28,"Jolie Dale","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (43,93,"Cullen Mack","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (44,8,"Colt Schwartz","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (45,46,"Myra Vincent","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (46,80,"Herman Malone","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (47,80,"Leandra Kane","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (48,30,"Avram Fischer","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (49,99,"Althea Waller","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (50,17,"Adrian Stewart","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (51,20,"Dai Turner","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (52,57,"Phelan Barnett","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (53,14,"Macon Wilkerson","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (54,45,"Erich Rogers","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (55,22,"Gretchen Waters","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (56,2,"Logan Maldonado","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (57,31,"Erica Bernard","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (58,46,"Hadassah Hamilton","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (59,31,"Zane Branch","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (60,35,"Tara Cameron","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (61,83,"Ina Olsen","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (62,60,"Constance Everett","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (63,96,"Dorian Lindsey","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (64,88,"Faith Fields","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (65,32,"Burton Mann","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (66,61,"Georgia Mayo","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (67,2,"Ashton Norris","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (68,71,"Venus Mayo","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (69,67,"Hilary Huber","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (70,49,"Lara Shepard","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (71,32,"Pearl Baxter","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (72,10,"Sybil Robinson","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (73,33,"Ciara Ochoa","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (74,2,"Chastity Lyons","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (75,4,"Henry Yates","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (76,24,"Abra Watkins","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (77,70,"Dexter Benjamin","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (78,45,"Cassandra Martinez","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (79,48,"Conan Reese","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (80,58,"Samson Ortega","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (81,32,"Germane Boyd","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (82,71,"Nash Hodge","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (83,92,"Mikayla Sampson","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (84,26,"Raphael Walsh","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (85,59,"Sopoline Chen","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (86,13,"Priscilla Small","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (87,92,"Yolanda Mathews","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (88,2,"Jillian Johns","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (89,43,"Xandra Dotson","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (90,6,"Malcolm Underwood","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (91,20,"Nathaniel Randolph","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (92,34,"Yoshio Levy","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (93,84,"Ciara Palmer","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (94,21,"Irma Mckinney","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (95,13,"Lars Garner","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (96,43,"Lenore Tucker","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (97,6,"Leslie Vinson","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (98,89,"Clayton Wood","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (99,82,"Velma Colon","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (100,36,"Savannah Glenn","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (101,100,"Kylynn Cain","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (102,28,"Xanthus Olsen","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (103,43,"Addison Pope","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (104,74,"Mona Berry","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (105,57,"Fiona Lowery","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (106,45,"Merritt Gallagher","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (107,73,"Allistair Ferguson","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (108,55,"Meredith Mills","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (109,46,"Marsden Tanner","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (110,51,"Iliana Walker","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (111,56,"Dustin Beach","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (112,17,"Iliana Baxter","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (113,36,"Kenyon Baldwin","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (114,9,"Nathaniel Riddle","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (115,18,"Zena Bridges","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (116,68,"Astra Dudley","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (117,54,"Josiah Lyons","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (118,52,"Kareem Sanchez","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (119,12,"Nevada Cox","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (120,17,"Minerva Mckee","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (121,27,"Bernard Fitzpatrick","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (122,26,"Nissim Finley","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (123,76,"Ira Mcmillan","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (124,19,"Serina Reynolds","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (125,71,"Sean Rutledge","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (126,82,"Alisa House","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (127,78,"Germaine Gonzales","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (128,95,"Zoe Bentley","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (129,41,"Barry Sanders","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (130,38,"Ferdinand Henderson","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (131,79,"Amelia Baldwin","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (132,13,"Yvonne Franks","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (133,26,"Tallulah Gallagher","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (134,56,"Claudia Rasmussen","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (135,10,"Chandler Downs","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (136,73,"Deborah Carlson","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (137,76,"Darryl Fox","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (138,67,"Porter Golden","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (139,55,"Ferris Osborn","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (140,12,"Abel Park","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (141,74,"Jason Graves","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (142,64,"Timothy Rojas","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (143,87,"Amal Sweet","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (144,10,"Wesley Rivas","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (145,18,"Jolene Kelly","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (146,11,"Abigail Hammond","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (147,7,"Lynn Walker","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (148,46,"Octavius House","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (149,33,"Raphael Meadows","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (150,45,"Alexandra Herman","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (151,65,"Dora Mccray","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (152,80,"Arden Carver","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (153,22,"Tana Hendrix","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (154,7,"Hillary Hunt","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (155,68,"Drake Gilbert","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (156,59,"Maisie Sanchez","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (157,19,"Iliana Reed","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (158,41,"Grant Wade","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (159,3,"Maggy Ramirez","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (160,34,"Lyle Lindsay","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (161,59,"Hope Cannon","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (162,87,"Fletcher Cortez","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (163,9,"Justine Russo","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (164,91,"Troy Diaz","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (165,33,"Cody Thornton","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (166,60,"Charity Byrd","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (167,78,"Owen Sargent","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (168,58,"Macon Barber","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (169,89,"Gavin Mcmillan","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (170,66,"Samantha Winters","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (171,33,"Aretha Snyder","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (172,4,"Ria Newman","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (173,86,"Theodore Owen","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (174,97,"Donovan Drake","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (175,93,"Ulysses Peck","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (176,40,"Regina Frank","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (177,16,"September Dawson","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (178,3,"Suki York","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (179,93,"Malcolm Mendez","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (180,65,"Xanthus Phelps","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (181,64,"Rhona Mcdowell","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (182,34,"Dennis Mcgowan","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (183,36,"Cole Blevins","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (184,85,"Hayes Odonnell","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (185,65,"Ethan Wilkinson","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (186,1,"Camden Howell","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (187,81,"Coby Washington","Responsable communication");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (188,42,"Rhiannon Mclaughlin","Directeur");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (189,77,"Galvin Vaughan","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (190,54,"Griffin Irwin","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (191,93,"Isaac Jefferson","Ressources Humaines");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (192,76,"Berk Blackwell","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (193,18,"Scarlett Potter","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (194,36,"Maisie Pacheco","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (195,96,"Vaughan Peterson","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (196,42,"Brenden Burnett","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (197,31,"Yoko Hayes","Assistant(e)");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (198,81,"Sonya Bass","Chef de projet");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (199,86,"MacKensie Langley","Secrétaire");
INSERT INTO contact_person (id,id_societe,nom_personne,poste) VALUES (200,17,"Emi Clarke","Ressources Humaines");